services:
  - type: web
    name: kasa-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kasa-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://kasa-case-study.vercel.app

databases:
  - name: kasa-db
    plan: free
